name: on-push
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run unit tests
        run: |
          npm install
          npm install jsdoc jsdoc2md rollup docsify typescript -g
          npm run build
