name: on-push
on: [push]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v14.16.0
      - run: npm install -g eslint
      - run: eslint --fix --no-ignore lib/**/*.ts test/**/*.ts
    